exports.staticLabel = {
    "en": {
        "LABELS": {},
        "error":{
            "error_1":"First name must be specified.",
            "error_2":"First name has non-alphanumeric characters.",
            "error_3":"Last name must be specified.",
            "error_4":"Last name has non-alphanumeric characters.",
            "error_5":"Email must be specified.",
            "error_6":"Email must be a valid email address.",
            "error_7":"E-mail already in use",
            "error_8":"Gender should not be empty.",
            "error_9":"Age should not be empty.",
            "error_10":"Mobile Number should not be empty.",
            "error_11":"Sorry, something went wrong. please try again later.",
            "error_12":"Password must be 6 characters or greater.",
            "error_13":"Password must be specified.",
            "error_14":"Account is not active. Please contact admin.",
            "error_15":"Account is not confirmed. Please confirm your account.",
            "error_16":"Email or Password wrong.",
            "error_17":"OTP must be specified.",
            "error_18":"Account confirmed success.",
            "error_19":"Otp does not match",
            "error_20":"Account already confirmed.",
            "error_21":"Specified email not found.",
            "error_22":"Confirm otp sent.",
            "error_23":"Operation success",
            "error_24":"Shop name must not be empty.",
            "error_25":"Shop description must not be empty.",
            "error_26":"Shop logo must not be empty.",
            "error_27":"Shop email id must not be empty.",
            "error_28":"Shop status must not be empty.",
            "error_29":"Shop location must not be empty.",
            "error_30":"Shop number must not be empty.",
            "error_31":"Shop street must not be empty.",
            "error_32":"Shop city must not be empty.",
            "error_33":"Shop state must not be empty.",
            "error_34":"Shop postal code must not be empty.",
            "error_35":"Shop country must not be empty.",
            "error_36":"Shop mobile number must not be empty.",
            "error_37":"Shop already registered, Please contact with Administrator.",
        }
    }
};

